version: '3.7'

services:
    web:
      build: .
      ports:
        - "8080:8080"
      volumes:
        - type: "volume"
          source: "dbpython"
          target: "/usr/db"
volumes:
  dbpython: