version: '3.7'

services:
    web:
      build: .
      depends_on:
        - db
      ports:
        - "8080:8080"

    db:
      image: mariadb
      restart: always
      volumes:
        - ./mysql:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: admin
        MYSQL_PASSWORD: test
        MYSQL_DATABASE: database