apiVersion: v1
kind: PersistentVolume
metadata:
    name: "pv1"
spec:
    capacity:
        storage: 10Gi
    accessModes:
        - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    portworxVolume:
        volumeID: "pv1"